<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php'; admin_start_session(); admin_require_authentication(); $database = portal_database();
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT) ?: 0; $card = ['title' => '', 'description' => '', 'url' => '', 'icon' => 'fas fa-globe', 'variant' => 'standard', 'badge_text' => '', 'badge_color' => '#ef4444', 'is_active' => 1];
if ($id) { $statement = $database->prepare('SELECT * FROM cards WHERE id = ?'); $statement->execute([$id]); $card = $statement->fetch(); if (!$card) { http_response_code(404); exit('Card not found.'); } }
$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') { admin_verify_csrf(); [$card, $errors] = portal_validate_card($_POST); if (!$errors) { if ($id) { $statement = $database->prepare('UPDATE cards SET title = :title, description = :description, url = :url, icon = :icon, variant = :variant, badge_text = :badge_text, badge_color = :badge_color, is_active = :is_active, updated_at = CURRENT_TIMESTAMP WHERE id = :id'); $card['id'] = $id; $statement->execute($card); admin_flash('message', 'Card updated.'); } else { $card['sort_order'] = (int) $database->query('SELECT COALESCE(MAX(sort_order), 0) + 1 FROM cards')->fetchColumn(); $statement = $database->prepare('INSERT INTO cards (title, description, url, icon, variant, badge_text, badge_color, is_active, sort_order) VALUES (:title, :description, :url, :icon, :variant, :badge_text, :badge_color, :is_active, :sort_order)'); $statement->execute($card); admin_flash('message', 'Card added.'); } header('Location: index.php'); exit; } }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $id ? 'Edit' : 'Add' ?> card | AIS</title><link rel="stylesheet" href="admin.css"></head><body class="admin-page"><main class="form-shell"><a class="back-link" href="index.php">&#8592; Portal cards</a><h1><?= $id ? 'Edit card' : 'Add card' ?></h1><?php if ($errors): ?><div class="notice error"><?php foreach ($errors as $error): ?><div><?= portal_escape($error) ?></div><?php endforeach; ?></div><?php endif; ?><form class="card-form" method="post"><input type="hidden" name="csrf_token" value="<?= portal_escape(admin_csrf_token()) ?>"><label>Title<input name="title" value="<?= portal_escape($card['title']) ?>" maxlength="100" required></label><label>Description<textarea name="description" maxlength="250" rows="3"><?= portal_escape($card['description']) ?></textarea></label><label>Link<input name="url" type="url" value="<?= portal_escape($card['url']) ?>" required></label><div class="form-grid"><label>Icon<select name="icon"><?php foreach (portal_allowed_icons() as $value => $name): ?><option value="<?= portal_escape($value) ?>" <?= $card['icon'] === $value ? 'selected' : '' ?>><?= portal_escape($name) ?></option><?php endforeach; ?></select></label><label>Style<select name="variant"><option value="standard" <?= $card['variant'] === 'standard' ? 'selected' : '' ?>>Standard</option><option value="hero" <?= $card['variant'] === 'hero' ? 'selected' : '' ?>>Blue feature</option><option value="highlight" <?= $card['variant'] === 'highlight' ? 'selected' : '' ?>>Outlined highlight</option></select></label></div><div class="form-grid"><label>Badge text<input name="badge_text" value="<?= portal_escape($card['badge_text']) ?>" maxlength="24" placeholder="Optional, e.g. NEW"></label><label>Badge color<input name="badge_color" type="color" value="<?= portal_escape($card['badge_color']) ?>"></label></div><label class="checkbox"><input type="checkbox" name="is_active" value="1" <?= $card['is_active'] ? 'checked' : '' ?>> Show this card on the public portal</label><div class="form-actions"><a class="button secondary" href="index.php">Cancel</a><button type="submit">Save card</button></div></form></main></body></html>
